doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Shared:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine'
                prefix: 'App\Shared\Infrastructure\Doctrine'
                alias: Shared
            Auth:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Auth/Infrastructure/Doctrine/Entity'
                prefix: 'App\Auth\Infrastructure\Doctrine\Entity'
                alias: Auth
            Voucher:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Voucher/Infrastructure/Doctrine/Entity'
                prefix: 'App\Voucher\Infrastructure\Doctrine\Entity'
                alias: Voucher
            Provider:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Provider/Infrastructure/Doctrine/Entity'
                prefix: 'App\Provider\Infrastructure\Doctrine\Entity'
                alias: Provider
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
