# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters: {
    app.email_from: '%env(APP_EMAIL_FROM)%',
    app.frontend_url: '%env(APP_FRONTEND_URL)%'
}

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Auth\Application\Handler\:
        resource: '../src/Auth/Application/Handler/'
        tags: [ 'messenger.message_handler' ]

    App\Voucher\Application\Handler\:
        resource: '../src/Voucher/Application/Handler/'
        tags: [ 'messenger.message_handler' ]

    App\Provider\Application\Handler\:
        resource: '../src/Provider/Application/Handler/'
        tags: [ 'messenger.message_handler' ]

    App\Auth\Domain\Repository\UserRepository:
        class: App\Auth\Infrastructure\Doctrine\Repository\DoctrineUserRepository

    App\Auth\Application\Handler\SendVerifyEmailOnUserRegisteredHandler:
        tags: [ 'messenger.message_handler' ]
        arguments:
            $emailFrom: '%app.email_from%'

    App\Auth\Application\Handler\SendVerifyEmailOnUserEmailChangeRequestedHandler:
        tags: [ 'messenger.message_handler' ]
        arguments:
            $emailFrom: '%app.email_from%'

    App\Provider\Application\Handler\SendProviderApprovedEmailHandler:
        tags: [ 'messenger.message_handler' ]
        arguments:
            $emailFrom: '%app.email_from%'

    App\Provider\Application\Handler\SendProviderInvitationEmailHandler:
        tags: [ 'messenger.message_handler' ]
        arguments:
            $emailFrom: '%app.email_from%'

    App\Voucher\Application\Handler\SendVoucherCreatedEmailHandler:
        tags: [ 'messenger.message_handler' ]
        arguments:
            $emailFrom: '%app.email_from%'

    App\Voucher\Application\Handler\SendVoucherTransferredEmailHandler:
        tags: [ 'messenger.message_handler' ]
        arguments:
            $emailFrom: '%app.email_from%'

    App\Auth\Infrastructure\Doctrine\Outbox\AuthOutboxDomainEventFactory:
        tags: ['app.outbox_domain_event_factory']

    App\Provider\Infrastructure\Doctrine\Outbox\ProviderOutboxDomainEventFactory:
        tags: ['app.outbox_domain_event_factory']

    App\Voucher\Infrastructure\Doctrine\Outbox\VoucherOutboxDomainEventFactory:
        tags: ['app.outbox_domain_event_factory']

    App\Shared\Infrastructure\Doctrine\Outbox\DoctrineOutboxProcessor:
        arguments:
            $factories: !tagged_iterator app.outbox_domain_event_factory

    App\Shared\Application\Transaction\TransactionManager:
        alias: App\Shared\Infrastructure\Doctrine\Transaction\DoctrineTransactionManager

    App\Auth\Infrastructure\Url\FrontendUrlCreator:
        arguments:
            $frontendUrl: '%app.frontend_url%'

    App\Provider\Infrastructure\Url\FrontendUrlCreator:
        arguments:
            $frontendUrl: '%app.frontend_url%'
